[project]
name = "ml-fraud"
version = "0.1.0"
description = "Analysis of SynSEPA dataset - primarily for ML monitoring."
readme = "README.md"
authors = [
    { email = "lewis.lea@cantab.net" }
]
requires-python = ">=3.14"
dependencies = [
    "duckdb>=1.5.5",
    "mypy>=2.3.1",
    "pandas>=3.0.6",
    "pathlib>=1.0.1",
    "ruff>=0.16.9",
]

[project.scripts]
ml-fraud = "ml_fraud:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "jupyter>=1.1.1",
    "jupyterlab>=4.6.4",
    "mypy>=2.3.1",
    "pytest>=9.1.1",
    "requests>=2.34.2",
    "ruff>=0.16.9",
]
examples = [
    "jupyter>=1.1.1",
    "matplotlib>=3.11.2",
    "seaborn>=0.13.2",
]

[tool.uv]
package = true
